Zero Hunger/Controllers/ZeroController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using Zero_Hunger.Models;

namespace Zero_Hunger.Controllers
{
    public class ZeroController : Controller
    {
        // GET: Zero
        public ActionResult Homepage()
        {
            return View();
        }
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult contact()
        {
            return View();
        }
        public ActionResult AddRequest()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddRequest(Request R)
        {
            var db = new zero_hungerEntities();
            var n = db.Requests.ToList();
            db.Requests.Add(R);
            db.SaveChanges();
            return View("ViewRequest",n);
        }        
        public ActionResult ViewRequest()
        {
            var db = new zero_hungerEntities();
            var R = db.Requests.ToList();
            return View(R);
        }
        public ActionResult AddEmployee()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddEmployee(Employee E)
        {
            var db = new zero_hungerEntities();
            db.Employees.Add(E);
            db.SaveChanges();
            return View("Index");
        }
        public ActionResult ViewEmployee()
        {
            var db = new zero_hungerEntities();
            var em = db.Employees.ToList();
            return View(em);
        }
        public ActionResult Assign(Request R)
        {
            var db = new zero_hungerEntities();
            var n = db.Employees.ToList();
            ViewBag.Id = R.Id;
            ViewBag.Rname = R.RestaurentName;
            ViewBag.Fname = R.FoodName;
            ViewBag.Q = R.Quantity;
            return View(n);
        }
        [HttpPost]
        public ActionResult Assign(Collection C)
        {
            var db = new zero_hungerEntities();
            db.Collections.Add(C);
            db.SaveChanges();
            return View("Index");
        }
        public ActionResult Collected()
        {
            var db = new zero_hungerEntities();
            var collections = db.Collections.ToList();
            return View(collections);
        }
       
    }
}

Zero Hunger/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title  Zero Hunger</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body style="background-color: #98FF98 ">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ZERO HUNGER", "Homepage", "Zero", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Empolyee", "ViewEmployee", "Zero")</li>
                    <li>@Html.ActionLink("Add Request", "AddRequest", "Zero")</li>
                    <li>@Html.ActionLink("View Request", "ViewRequest", "Zero")</li>
                    <li>@Html.ActionLink("View Collected Requests", "Collected", "Zero")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content position:absolute">
        @RenderBody()
        <hr />
        <!-- Footer -->
        <footer class="text-center text-lg-dark bbg-success text-muted">
            <!-- Section: Social media -->
            <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
            </section>
            <!-- Section: Social media -->
            <!-- Section: Links  -->
            <section class="">
                <div class="container text-center text-md-start mt-5">
                    <!-- Grid row -->
                    <div class="row mt-3">
                        <!-- Grid column -->
                        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                            <!-- Content -->
                            <h4 class="text-uppercase fw-bold mb-4 text-dark">
                                <i class="fas fa-gem me-3"></i>Zero Hunger
                            </h4>
                            <p>
                                We've established an organization dedicated to providing nourishment to underprivileged individuals and children. We've noticed a significant amount of food wastage occurring daily in Dhaka city, particularly in office events and buffets. Our mission is to repurpose these surplus foods for the benefit of those in need.
                            </p>
                        </div>
                        <!-- Grid column -->
                        <!-- Grid column -->
                        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                            <!-- Links -->
                            <h4 class="text-uppercase fw-bold mb-4 text-dark">
                                Future Work
                            </h4>
                            <p>
                                <a href="#!" class="text-reset">Free Education</a>
                            </p>
                            <p>
                                <a href="#!" class="text-reset">Free Helth service</a>
                            </p>
                            <p>
                                <a href="#!" class="text-reset">Free Traning</a>
                            </p>
                            
                        </div>
                        <!-- Grid column -->
                        <!-- Grid column -->
                        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4 text-dark">
                            <!-- Links -->
                            <h4 class="text-uppercase fw-bold mb-4">
                                Useful links
                            </h4>
                            <p>
                                <a href="#!" class="text-reset">Donation</a>
                            </p>
                            <!----<p>
                                <a @Html.ActionLink("Send Message", "contact", "Zero")</a>
                            </p> -->
                            <p>
                                <a href="#!" class="text-reset">FQA</a>
                            </p>
                            <p>
                                <a href="#!" class="text-reset">Help</a>
                            </p>
                        </div>
                        <!-- Grid column -->
                        <!-- Grid column -->
                        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                            <!-- Links -->
                            <h4 class="text-uppercase fw-bold mb-4 text-dark">Contact</h4>
                            <p><i class="fas fa-home me-3"></i> Bansree, Rampura, Dhaka, Bangladesh</p>
                            <p>
                                <i class="fas fa-envelope me-3"></i>
                                ashiksarkar.bd@gmail.com
                            </p>
                            <p><i class="fas fa-phone me-3"></i>01716732950</p>
                            <p><i class="fas fa-print me-3"></i>01975319675</p>
                        </div>
                        <!-- Grid column -->
                    </div>
                    <!-- Grid row -->
                </div>
            </section>
            <!-- Section: Links  -->
            <!-- Copyright -->
            <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
                © 2022 Copyright:
                <a class="text-reset fw-bold" href="https://www.globalgoals.org/goals/2-zero-hunger/">Zerohunger</a>
            </div>
            <!-- Copyright -->
        </footer>
        <!-- Footer -->
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>